### ISSUE TITLE
Gdu hangs (100% cpu) when entering a folder with only empty files.

### ISSUE THREAD

**Issue by borestad** [dundee/gdu#368] opened 2024-06-14 19:22 UTC
**Describe the bug**
Gdu hangs (100% cpu) when entering a folder with only empty files.
It also crashes when starting normally and navigating to a folder with the same empty files.
Is only killable via killall / kill -9 etc.

**To Reproduce**

`mkdir -p /tmp/foo && cd $_ && touch a b c d && gdu`

**Expected behavior**
It shouldn't crash

**Screenshots**
<img width="839" alt="image" src="https://github.com/dundee/gdu/assets/286455/675db304-0ba0-490c-a6aa-82e1c8a105aa">
<img width="670" alt="image" src="https://github.com/dundee/gdu/assets/286455/f444d3c6-cb3a-4fed-9a8c-a7ad332705e1">

**System (please complete the following information):**
 - OS: Debian 12 / x86
 - Terminal iTerm
 - Version v5.28.0

**Additional context**
Version that I use - https://github.com/dundee/gdu/releases/download/v5.28.0/gdu_linux_amd64_static.tgz

**Comment by dundee** [comment] 2024-06-17 08:33
I am not able to reproduce that. Could you retry without the `-x` option?

**Comment by dundee** [comment] 2024-06-17 09:42
Found it. This was fixed in https://github.com/dundee/gdu/pull/359, I will release 5.29.0 soon.

**Closed by dundee** 2024-06-17 09:42 UTC
Labels: bug

**Comment by borestad** [comment] 2024-06-17 12:43
Amazing! ❤️
